#!/usr/bin/env python
# -*- coding: utf-8 -*-
import yaml
import os
import sys
import pygame
from pygame.locals import *

#The following slightly convoluted import block allows the game to run from the source tree for development
#When you do so, the local source paths take precedence over the installed paths.
#TODO: Add a windows check and alter default paths to work on that platform.
exepath = os.path.abspath(__file__)
gamedir = None
if exepath == '/usr/games/mirthless':
    settingsfile = '/etc/mirthless/mirthless.cfg'
else:
    settingsfile = os.path.dirname(exepath)+'/../../etc/mirthless/mirthless.cfg'
    gamedir =  os.path.abspath(os.path.dirname(exepath)+'/../share/mirthless')

if os.path.exists('/etc/mirthless/mirthless.cfg'):
    settingsfile = '/etc/mirthless/mirthless.cfg'
settingstr = open(settingsfile).read()

settings = yaml.load(settingstr)

if gamedir is None:
    gamedir = settings['gamedir']

sys.path.append(os.path.join(gamedir,'lib'))
from graphics import get_screen, Mapview, Tilemap, Button, EventStack
import util

def hello():
    print "Hello world"

if __name__ == "__main__":
    util.gamedir = gamedir
    quit = False
    pygame.init()
    screen = get_screen(settings['res_x'], settings['res_y'], settings['hardware_buffer'], settings['fullscreen'])  
    pygame.display.set_caption('Mirthless RPG')

    tilemap = Tilemap(util.file_path('images','roguelikeDungeon_transparent.png'),16,16)

    mapview = Mapview(tilemap, 10, 10)
    mapview.set_bg(0,0,2,5)
    eventstack =EventStack()
    quit_button = Button("Quit", sys.exit, eventstack, (0,0))
    yes_button = Button("Yes", hello, eventstack, (30,50))
    sprites = pygame.sprite.RenderUpdates()
    sprites.add(quit_button)
    sprites.add(yes_button)
    background = screen.copy()

        
    while not quit:       
        for event in pygame.event.get():
            if event.type == pygame.QUIT or event.type == KEYDOWN: 
                quit = True
            eventstack.handle_event(event)
        sprites.clear(screen, background)
        dirty = sprites.draw(screen)
        #overlays.draw(screen)
        pygame.display.update(dirty)
        #clock.tick(15)
        screen.blit(mapview.surface,(100,100))
        pygame.display.flip()




    

    





